### ISSUE TITLE
Is it mandatory to include "SQLitePlugin.js"?

### ISSUE THREAD

**Issue by svranch** [brodybits/cordova-sqlite-ext-bootstrap-starter#1]
I have a quick question.  i am looking at this link which brodybits included in the README for the main cordova-sqlite-storage repo: 

    >> You can find some more details in a nice writeup (though with old links and package names): http://iphonedevlog.wordpress.com/2014/04/07/installing-chris-brodys-sqlite-database-with-cordova-cli-android/.  <<

In his instructions, he uses this include:
   `<script type="text/javascript" charset="utf-8" src="SQLitePlugin.js"></script>`

However, you do not include it in the index file for the bootstrap starter app.  

So I am confused as to whether or not it is required?

thanks!

- Sandi

**Comment by brody2consult** [comment]
This is no longer required. The article is nice but out of date. It may be time to just replace it with a link to a more recent tutorial.

**Comment by svranch** [comment]
thank you.
