### ISSUE TITLE
How to make this work for encrypted (sqlcipher) databases ?

### ISSUE THREAD

**Issue by SwethaEnixta** [brodybits/cordova-sqlite-ext-bootstrap-starter#2]
Hi @brodybits 
I have used the below sample codes for creating separate Apps & they work fine
1. Cordova-sqlcipher-adapter-cipher-ext-master
2. cordova-sqlite-ext-bootstrap-starter-app

But I cannot access a pre-existing encrypted database using sqlcipher-adapter code. 
And I cannot access an encrypted db using the sqlite-ext code. 

Please suggest what is the best way to read from a pre-existing encrypted database using the above code bases ?

**Comment by brody2consult** [comment]
> But I cannot access a pre-existing encrypted database using sqlcipher-adapter code.

See <https://github.com/litehelpers/Cordova-sqlcipher-adapter/issues/11>

Alternative is to copy pre-existing encrypted database using cordova-plugin-file.
